shinyServer(function(input, output) {
  callModule(home, 'one')
  callModule(delivery, 'one')
  callModule(demand, 'one')
  callModule(elevation_change, 'one')
  callModule(casgem_data, 'one')
  callModule(model_aw, 'one')
  callModule(crops, 'one')
  callModule(water_balance, 'one')
})
