navbarPage(
  title = 'Solano County',
  theme = shinytheme(theme = 'paper'),
  header = includeCSS('styles.css'),
  tabPanel(title = 'Home',
           homeUI('one')),
  tabPanel(title = 'Deliveries',
           deliveryUI('one')),
  navbarMenu(title = 'Agriculture',
             tabPanel(title = 'Crops',
                      cropsUI('one')),
             tabPanel(title = 'Water Demand - By Crop Type',
                      model_awUI('one')),
             tabPanel(title = 'Water Demand - By Entity or Region',
                      demandUI('one'))),
  tabPanel(title = 'Groundwater',
           elevation_changeUI('one')),
  tabPanel(title = 'Water Balance',
           water_balanceUI('one'))
)
